<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DSPs [
<!--EDIT ONLY IN THE TXT FILE-->
<!--EXTERNAL DTD CALL DOES NOT PASS TO DOM-->
<!ELEMENT DSPs (Provider)>
<!ELEMENT Provider (Name, LastUpdated+, MapZoom?, Website?, ContactName?, ContactEmail?, Office+)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT LastUpdated (#PCDATA)>
<!ELEMENT MapZoom (#PCDATA)>
<!ELEMENT Website (#PCDATA)>
<!ELEMENT ContactName (#PCDATA)>
<!ELEMENT ContactEmail (#PCDATA)>
<!ELEMENT Office (Lat, Lng, Street, City, State, Zip, Phone, Fax)>
<!ELEMENT Lat (#PCDATA)>
<!ELEMENT Lng (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Fax (#PCDATA)>
<!ELEMENT Service (Locations?)>
<!ELEMENT FIPs (#PCDATA)>
<!-- Attribute Definitions-->
<!ATTLIST Provider id CDATA #REQUIRED>
<!ATTLIST Service serviceName CDATA #IMPLIED>
<!ATTLIST Service serviceZoom CDATA #IMPLIED>
<!ATTLIST Service serviceNote CDATA #IMPLIED>
<!ATTLIST FIPs travelReq (Y|N) "N">
<!ATTLIST FIPS languages CDATA #IMPLIED>
]>
<DSPs>
    <Provider id="0">
        <Name>Oceanside Evaluations</Name>
        <LastUpdated>2021-04-26</LastUpdated>
        <MapZoom>1</MapZoom>
        <Website>www.oceansideevaluations.com/</Website>
        <ContactName>Ann P. VanSkiver, Psy.D., NCSP</ContactName>
        <ContactEmail>avanskiver@oceansideevaluations.com</ContactEmail>
        <Office>
            <Lat/>
            <Lng/>
            <Street>115A Bulifants Blvd.</Street>
            <City>Williamsburg</City>
            <State>VA</State>
            <Zip>23188</Zip>
            <Phone>(757) 771-0269</Phone>
            <Fax>(757) 528-8668</Fax>
        </Office>
        <Service serviceName="Psychological Evaluation" serviceZoom="1">
            <FIPs travelReq="Y">51036</FIPs>
            <FIPs travelReq="N">51095</FIPs>
            <FIPs travelReq="N">51199</FIPs>
            <FIPs travelReq="N">51735</FIPs>
            <FIPs travelReq="N">51127</FIPs>
            <FIPs travelReq="N">51101</FIPs>
            <FIPs travelReq="Y">51085</FIPs>
            <FIPs travelReq="N">51097</FIPs>
            <FIPs travelReq="N">51073</FIPs>
            <FIPs travelReq="N">51115</FIPs>
            <FIPs travelReq="N">51119</FIPs>
            <FIPs travelReq="Y">51103</FIPs>
            <FIPs travelReq="N">51830</FIPs>
            <FIPs travelReq="Y">51650</FIPs>
            <FIPs travelReq="Y">51700</FIPs>
            <FIPs travelReq="Y">51133</FIPs>
            <FIPs travelReq="Y">51159</FIPs>
            <FIPs travelReq="Y">51057</FIPs>
        <FIPs travelReq="Y">51181</FIPs></Service>
        <Service serviceName="Individual/ Family Counseling" serviceZoom="1">
            <FIPs travelReq="Y">51036</FIPs>
            <FIPs travelReq="N">51095</FIPs>
            <FIPs travelReq="N">51199</FIPs>
            <FIPs travelReq="N">51735</FIPs>
            <FIPs travelReq="Y">51073</FIPs>
            <FIPs travelReq="N">51127</FIPs>
            <FIPs travelReq="Y">51097</FIPs>
            <FIPs travelReq="Y">51101</FIPs>
        </Service>
        <Service serviceName="Mental Health Evaluation" serviceZoom="1">
            <FIPs travelReq="Y">51036</FIPs>
            <FIPs travelReq="N">51095</FIPs>
            <FIPs travelReq="N">51199</FIPs>
            <FIPs travelReq="N">51735</FIPs>
            <FIPs travelReq="N">51127</FIPs>
            <FIPs travelReq="N">51101</FIPs>
            <FIPs travelReq="Y">51085</FIPs>
            <FIPs travelReq="N">51097</FIPs>
            <FIPs travelReq="N">51073</FIPs>
            <FIPs travelReq="N">51115</FIPs>
            <FIPs travelReq="N">51119</FIPs>
            <FIPs travelReq="Y">51103</FIPs>
            <FIPs travelReq="N">51830</FIPs>
            <FIPs travelReq="N">51650</FIPs>
            <FIPs travelReq="N">51700</FIPs>
            <FIPs travelReq="Y">51133</FIPs>
            <FIPs travelReq="Y">51159</FIPs>
            <FIPs travelReq="Y">51057</FIPs>
        </Service>
    </Provider>
    <Provider id="1">
        <Name>Fulcrum Counselors, LLC</Name>
        <LastUpdated>2021-08-25</LastUpdated>
        <MapZoom>-1</MapZoom>
        <Website>fulcrumcounselors.com/</Website>
        <ContactName>Glenn Fowlkes</ContactName>
        <ContactEmail>gfowlkes@fulcrumcounselors.com</ContactEmail>
        <Office>
            <Lat>37.2444493</Lat>
            <Lng>-78.44331019999998</Lng>
            <Street>5301 Farmville Road</Street>
            <City>Farmville</City>
            <State>VA</State>
            <Zip>23901</Zip>
            <Phone>(434) 298-7318</Phone>
            <Fax/>
        </Office>
        <Service serviceName="Youth with Sexualized Behaviors (YSB) Treatment" serviceZoom="-1">
            <FIPs travelReq="N">51003</FIPs>
            <FIPs travelReq="N">51540</FIPs>
            <FIPs travelReq="Y">51065</FIPs>
            <FIPs travelReq="Y">51075</FIPs>
            <FIPs travelReq="Y">51047</FIPs>
            <FIPs travelReq="Y">51113</FIPs>
            <FIPs travelReq="Y">51079</FIPs>
            <FIPs travelReq="N">51109</FIPs>
            <FIPs travelReq="Y">51137</FIPs>
            <FIPs travelReq="Y">51009</FIPs>
            <FIPs travelReq="N">51125</FIPs>
            <FIPs travelReq="N">51031</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="N">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="Y">51025</FIPs>
            <FIPs travelReq="N">51670</FIPs>
            <FIPs travelReq="N">51011</FIPs>
            <FIPs travelReq="N">51029</FIPs>
            <FIPs travelReq="N">51049</FIPs>
            <FIPs travelReq="N">51037</FIPs>
            <FIPs travelReq="Y">51111</FIPs>
            <FIPs travelReq="N">51083</FIPs>
            <FIPs travelReq="Y">51117</FIPs>
            <FIPs travelReq="N">51147</FIPs>
            <FIPs travelReq="N">51007</FIPs>
            <FIPs travelReq="Y">51053</FIPs>
            <FIPs travelReq="N">51135</FIPs>
            <FIPs travelReq="N">51730</FIPs>
            <FIPs travelReq="N">51145</FIPs>
            <FIPs travelReq="N">51041</FIPs>
            <FIPs travelReq="N">51570</FIPs>
            <FIPs travelReq="N">51760</FIPs>
            <FIPs travelReq="Y">51087</FIPs>
        </Service>
        <Service serviceName="Psycho-Sexual Evaluation" serviceZoom="-1">
            <FIPs travelReq="N">51003</FIPs>
            <FIPs travelReq="N">51540</FIPs>
            <FIPs travelReq="Y">51065</FIPs>
            <FIPs travelReq="Y">51075</FIPs>
            <FIPs travelReq="Y">51047</FIPs>
            <FIPs travelReq="Y">51113</FIPs>
            <FIPs travelReq="Y">51079</FIPs>
            <FIPs travelReq="N">51109</FIPs>
            <FIPs travelReq="Y">51137</FIPs>
            <FIPs travelReq="Y">51009</FIPs>
            <FIPs travelReq="N">51125</FIPs>
            <FIPs travelReq="N">51031</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="N">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="Y">51025</FIPs>
            <FIPs travelReq="N">51670</FIPs>
            <FIPs travelReq="N">51011</FIPs>
            <FIPs travelReq="N">51029</FIPs>
            <FIPs travelReq="N">51049</FIPs>
            <FIPs travelReq="N">51037</FIPs>
            <FIPs travelReq="Y">51111</FIPs>
            <FIPs travelReq="N">51083</FIPs>
            <FIPs travelReq="Y">51117</FIPs>
            <FIPs travelReq="N">51147</FIPs>
            <FIPs travelReq="N">51007</FIPs>
            <FIPs travelReq="Y">51053</FIPs>
            <FIPs travelReq="N">51135</FIPs>
            <FIPs travelReq="N">51730</FIPs>
            <FIPs travelReq="N">51145</FIPs>
            <FIPs travelReq="N">51041</FIPs>
            <FIPs travelReq="N">51570</FIPs>
            <FIPs travelReq="N">51760</FIPs>
            <FIPs travelReq="Y">51087</FIPs>
        </Service>
        <Service serviceName="Mental Health Evaluation" serviceZoom="-1">
            <FIPs travelReq="N">51003</FIPs>
            <FIPs travelReq="N">51540</FIPs>
            <FIPs travelReq="Y">51065</FIPs>
            <FIPs travelReq="Y">51075</FIPs>
            <FIPs travelReq="Y">51079</FIPs>
            <FIPs travelReq="N">51109</FIPs>
            <FIPs travelReq="Y">51009</FIPs>
            <FIPs travelReq="N">51125</FIPs>
            <FIPs travelReq="N">51031</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="N">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="Y">51025</FIPs>
            <FIPs travelReq="N">51670</FIPs>
            <FIPs travelReq="N">51011</FIPs>
            <FIPs travelReq="N">51029</FIPs>
            <FIPs travelReq="N">51049</FIPs>
            <FIPs travelReq="N">51037</FIPs>
            <FIPs travelReq="Y">51111</FIPs>
            <FIPs travelReq="N">51083</FIPs>
            <FIPs travelReq="Y">51117</FIPs>
            <FIPs travelReq="N">51147</FIPs>
            <FIPs travelReq="N">51007</FIPs>
            <FIPs travelReq="Y">51053</FIPs>
            <FIPs travelReq="N">51135</FIPs>
            <FIPs travelReq="N">51730</FIPs>
            <FIPs travelReq="N">51145</FIPs>
            <FIPs travelReq="N">51041</FIPs>
            <FIPs travelReq="N">51570</FIPs>
            <FIPs travelReq="N">51760</FIPs>
            <FIPs travelReq="Y">51087</FIPs>
        </Service>
        <Service serviceName="Trauma-Focused Cognitive Behavioral Therapy (TF-CBT)" serviceZoom="-1">
            <FIPs travelReq="N">51003</FIPs>
            <FIPs travelReq="N">51540</FIPs>
            <FIPs travelReq="Y">51065</FIPs>
            <FIPs travelReq="Y">51075</FIPs>
            <FIPs travelReq="Y">51047</FIPs>
            <FIPs travelReq="Y">51113</FIPs>
            <FIPs travelReq="Y">51079</FIPs>
            <FIPs travelReq="N">51109</FIPs>
            <FIPs travelReq="Y">51137</FIPs>
            <FIPs travelReq="Y">51009</FIPs>
            <FIPs travelReq="N">51125</FIPs>
            <FIPs travelReq="N">51031</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="N">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="Y">51025</FIPs>
            <FIPs travelReq="N">51670</FIPs>
            <FIPs travelReq="N">51011</FIPs>
            <FIPs travelReq="N">51029</FIPs>
            <FIPs travelReq="N">51049</FIPs>
            <FIPs travelReq="N">51037</FIPs>
            <FIPs travelReq="Y">51111</FIPs>
            <FIPs travelReq="N">51083</FIPs>
            <FIPs travelReq="Y">51117</FIPs>
            <FIPs travelReq="N">51147</FIPs>
            <FIPs travelReq="N">51007</FIPs>
            <FIPs travelReq="Y">51053</FIPs>
            <FIPs travelReq="N">51135</FIPs>
            <FIPs travelReq="N">51730</FIPs>
            <FIPs travelReq="N">51145</FIPs>
            <FIPs travelReq="N">51041</FIPs>
            <FIPs travelReq="N">51570</FIPs>
            <FIPs travelReq="N">51760</FIPs>
            <FIPs travelReq="Y">51087</FIPs>
        </Service>
    </Provider>
    <Provider id="2">
        <Name>ANCHOR Commission</Name>
        <LastUpdated>2021-08-24</LastUpdated>
        <MapZoom>2</MapZoom>
        <Website>www.anchor-services.org </Website>
        <ContactName>Ricky Walker</ContactName>
        <ContactEmail>ricky.walker@anchor-services.org</ContactEmail>
        <Office>
            <Lat>36.6861604</Lat>
            <Lng>-79.86675200000002</Lng>
            <Street>313 East Market Street</Street>
            <City>Martinsville</City>
            <State>VA</State>
            <Zip>24112</Zip>
            <Phone>(276) 634-2910</Phone>
            <Fax>(276) 634-5375</Fax>
        </Office>
        <Service serviceName="Substance Abuse Service" serviceZoom="2">
            <FIPs travelReq="Y">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="N">51089</FIPs>
            <FIPs travelReq="N">51690</FIPs>
            <FIPs travelReq="N">51141</FIPs>
            <FIPs travelReq="Y">51067</FIPs>
            <FIPs travelReq="Y">51775</FIPs>
            <FIPs travelReq="Y">51161</FIPs>
            <FIPs travelReq="Y">51770</FIPs>
            <FIPs travelReq="Y">51063</FIPs>
            <FIPs travelReq="Y">51640</FIPs>
            <FIPs travelReq="Y">51035</FIPs>
            <FIPs travelReq="Y">51077</FIPs>
        </Service>
        <Service serviceName="Electronic Monitoring" serviceZoom="2">
            <FIPs travelReq="Y">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="N">51089</FIPs>
            <FIPs travelReq="N">51690</FIPs>
            <FIPs travelReq="N">51141</FIPs>
            <FIPs travelReq="Y">51067</FIPs>
            <FIPs travelReq="Y">51775</FIPs>
            <FIPs travelReq="Y">51161</FIPs>
            <FIPs travelReq="Y">51770</FIPs>
            <FIPs travelReq="Y">51063</FIPs>
            <FIPs travelReq="Y">51640</FIPs>
            <FIPs travelReq="Y">51035</FIPs>
            <FIPs travelReq="Y">51077</FIPs>
            <FIPs travelReq="Y">51191</FIPs>
            <FIPs travelReq="Y">51520</FIPs>
            <FIPs travelReq="Y">51173</FIPs>
            <FIPs travelReq="Y">51197</FIPs>
            <FIPs travelReq="Y">51155</FIPs>
            <FIPs travelReq="Y">51750</FIPs>
            <FIPs travelReq="Y">51121</FIPs>
            <FIPs travelReq="Y">51019</FIPs>
            <FIPs travelReq="Y">51031</FIPs>
            <FIPs travelReq="Y">51680</FIPs>
            <FIPs travelReq="Y">51083</FIPs>
            <FIPs travelReq="Y">51023</FIPs>
        </Service>
        <Service serviceName="Clinical Group" serviceZoom="2">
            <FIPs travelReq="Y">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="N">51089</FIPs>
            <FIPs travelReq="N">51690</FIPs>
            <FIPs travelReq="N">51141</FIPs>
            <FIPs travelReq="Y">51067</FIPs>
            <FIPs travelReq="Y">51775</FIPs>
            <FIPs travelReq="Y">51161</FIPs>
            <FIPs travelReq="Y">51770</FIPs>
            <FIPs travelReq="Y">51063</FIPs>
            <FIPs travelReq="Y">51640</FIPs>
            <FIPs travelReq="Y">51035</FIPs>
            <FIPs travelReq="Y">51077</FIPs>
        </Service>
        <Service serviceName="Seven Challenges for Substance Abuse" serviceZoom="2">
            <FIPs travelReq="Y">51143</FIPs>
            <FIPs travelReq="Y">51590</FIPs>
            <FIPs travelReq="N">51089</FIPs>
            <FIPs travelReq="N">51690</FIPs>
            <FIPs travelReq="N">51141</FIPs>
            <FIPs travelReq="Y">51067</FIPs>
            <FIPs travelReq="Y">51775</FIPs>
            <FIPs travelReq="Y">51161</FIPs>
            <FIPs travelReq="Y">51770</FIPs>
            <FIPs travelReq="Y">51063</FIPs>
            <FIPs travelReq="Y">51640</FIPs>
            <FIPs travelReq="Y">51035</FIPs>
            <FIPs travelReq="Y">51077</FIPs>
        </Service>
    </Provider>
    <Provider id="3">
        <Name>Blue Ridge Behavioral Healthcare</Name>
        <LastUpdated>2021-09-23</LastUpdated>
        <MapZoom>-1</MapZoom>
        <Website>www.brbh.org</Website>
        <ContactName>Cathy L. Brown, LCSW</ContactName>
        <ContactEmail>cbrown@brbh.org</ContactEmail>
        <Office>
            <Lat>37.2617967</Lat>
            <Lng>-79.94710099999999</Lng>
            <Street>1315 Franklin Rd. SW</Street>
            <City>Roanoke</City>
            <State>VA</State>
            <Zip>24016</Zip>
            <Phone>(540) 981-1102 ext. 2248</Phone>
            <Fax>(540) 344-4169</Fax>
        </Office>
        <Service serviceName="Substance Abuse Service" serviceZoom="1">
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N" languages="Farsi, Spanish">51770</FIPs>
            <FIPs travelReq="N" languages="Farsi, Spanish">51045</FIPs>
            <FIPs travelReq="N" languages="">51023</FIPs>
            <FIPs travelReq="N" languages="Farsi, Spanish">51775</FIPs>
        </Service>
        <Service serviceName="Individual/ Family Counseling" serviceZoom="1">
            <!-- Craig and Botetourt -->
            <FIPs travelReq="N">51045</FIPs>
            <FIPs travelReq="N" languages="Farsi, Spanish">51023</FIPs>
            <!-- All of CSU23 -->
            <FIPs travelReq="N" languages="Farsi, Spanish">51161</FIPs>
            <FIPs travelReq="N">51775</FIPs>
            <!-- CSU23A Roanoke -->
            <FIPs travelReq="N">51770</FIPs>
        </Service>
        <Service serviceName="Mental Health Evaluation" serviceZoom="1">
            <!-- Craig and Botetourt -->
            <FIPs travelReq="N">51045</FIPs>
            <FIPs travelReq="N" languages="Farsi, Spanish">51023</FIPs>
            <!-- All of CSU23 -->
            <FIPs travelReq="N" languages="Farsi, Spanish">51161</FIPs>
            <FIPs travelReq="N">51775</FIPs>
            <!-- CSU23A Roanoke -->
            <FIPs travelReq="N">51770</FIPs>
        </Service>
        <Service serviceName="HFW Intensive Care Coordination" serviceZoom="1">
            <!-- Craig and Botetourt -->
            <FIPs travelReq="N">51045</FIPs>
            <FIPs travelReq="N">51023</FIPs>
            <!-- All of CSU23 -->
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51775</FIPs>
            <!-- CSU23A Roanoke -->
            <FIPs travelReq="N">51770</FIPs>
        </Service>
        <Service serviceName="Functional Family Therapy (FFT)" serviceZoom="1">
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N" languages="Farsi, Spanish">51045</FIPs>
            <FIPs travelReq="N" languages="Farsi, Spanish">51023</FIPs>
            <FIPs travelReq="N">51775</FIPs>
        </Service>
        <Service serviceName="Trauma-Focused Cognitive Behavioral Therapy (TF-CBT)" serviceZoom="1">
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N">51045</FIPs>
            <FIPs travelReq="N">51023</FIPs>
            <FIPs travelReq="N">51775</FIPs>
        </Service>
        <Service serviceName="Specialized Individual Therapy (DBT/ EMDR)" serviceZoom="1">
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N">51045</FIPs>
            <FIPs travelReq="N">51023</FIPs>
            <FIPs travelReq="N">51775</FIPs>
        </Service>
        <Service serviceName="Substance Abuse Evaluation" serviceZoom="1">
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N">51045</FIPs>
            <FIPs travelReq="N">51023</FIPs>
            <FIPs travelReq="N">51775</FIPs>
        </Service>
    </Provider>
    <Provider id="4">
        <Name>DePaul Community Resources</Name>
        <LastUpdated>2021-08-25</LastUpdated>
        <MapZoom>-1</MapZoom>
        <Website>www.depaulcr.org/</Website>
        <ContactName>Jason Poston, LCSW, LSATP, CSAC, CSOTP, MAC</ContactName>
        <ContactEmail>JPoston@depaulcr.org</ContactEmail>
        <Office>
            <Lat>36.6962763</Lat>
            <Lng>-81.97299869999999</Lng>
            <Street>106 Abingdon Place</Street>
            <City>Abingdon</City>
            <State>VA</State>
            <Zip>24211</Zip>
            <Phone>276-623-0881</Phone>
            <Fax>276.623.0002</Fax>
        </Office>
        <Office>
            <Lat>37.3430896</Lat>
            <Lng>-79.9256305</Lng>
            <Street>5650 Hollins Road</Street>
            <City>Roanoke</City>
            <State>VA</State>
            <Zip>24019</Zip>
            <Phone>540-265-8923</Phone>
            <Fax>540-265-7663</Fax>
        </Office>
        <Office>
            <Lat>37.045484</Lat>
            <Lng>-81.7844693</Lng>
            <Street>2677 Steelsburg Highway, Suite 10</Street>
            <City>Cedar Bluff</City>
            <State>VA</State>
            <Zip>24609</Zip>
            <Phone>276-963-2360</Phone>
            <Fax>540-963-2363</Fax>
        </Office>
        <Office>
            <Lat>38.0695754</Lat>
            <Lng>-78.4684676</Lng>
            <Street>1020 Carrington Place, Suite 100</Street>
            <City>Charlottesville</City>
            <State>VA</State>
            <Zip>22901</Zip>
            <Phone>434-977-9847</Phone>
            <Fax>434-977-2809</Fax>
        </Office>
        <Office>
            <Lat>37.1288855</Lat>
            <Lng>-80.4065045</Lng>
            <Street>106 Franklin Street</Street>
            <City>Christiansburg</City>
            <State>VA</State>
            <Zip>24073</Zip>
            <Phone>540-381-1848</Phone>
            <Fax>540-381-5372</Fax>
        </Office>
        <Office>
            <Lat>37.3379981</Lat>
            <Lng>-79.27264339999999</Lng>
            <Street>4859 Waterlick Road</Street>
            <City>Forest</City>
            <State>VA</State>
            <Zip>24551</Zip>
            <Phone>434-455-3727</Phone>
            <Fax>434-455-2891</Fax>
        </Office>
        <Service serviceZoom="-1" serviceName="Individual/ Family Counseling">
            <FIPs travelReq="N">51173</FIPs>
            <FIPs travelReq="N">51191</FIPs>
            <FIPs travelReq="N">51167</FIPs>
            <FIPs travelReq="N">51185</FIPs>
            <FIPs travelReq="N">51121</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N">51520</FIPs>
            <FIPs travelReq="N">51750</FIPs>
            <FIPs travelReq="N">51155</FIPs>
            <FIPs travelReq="N">51775</FIPs>
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51003</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="Y">51019</FIPs>
            <FIPs travelReq="N">51009</FIPs>
            <FIPs travelReq="N">51540</FIPs>
            <FIPs travelReq="Y">51197</FIPs>
            <FIPs travelReq="Y">51021</FIPs>
            <FIPs travelReq="N">51071</FIPs>
            <FIPs travelReq="Y">51169</FIPs>
            <FIPs travelReq="Y">51023</FIPs>
            <FIPs travelReq="Y">51079</FIPs>
            <FIPs travelReq="Y">51109</FIPs>
            <FIPs travelReq="Y">51065</FIPs>
            <FIPs travelReq="Y">51125</FIPs>
            <FIPs travelReq="Y">51820</FIPs>
            <FIPs travelReq="Y">51015</FIPs>
        </Service>
        <Service serviceZoom="-1" serviceName="Substance Abuse Service">
            <FIPs travelReq="N">51191</FIPs>
            <FIPs travelReq="N">51167</FIPs>
            <FIPs travelReq="N">51185</FIPs>
            <FIPs travelReq="N">51173</FIPs>
            <FIPs travelReq="N">51520</FIPs>
            <FIPs travelReq="Y">51169</FIPs>
        </Service>
        <Service serviceZoom="-1" serviceName="Clinical Group">
            <FIPs travelReq="N">51167</FIPs>
            <FIPs travelReq="N">51185</FIPs>
            <FIPs travelReq="N">51173</FIPs>
            <FIPs travelReq="N">51191</FIPs>
            <FIPs travelReq="N">51155</FIPs>
            <FIPs travelReq="N">51071</FIPs>
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N">51520</FIPs>
            <FIPs travelReq="N">51775</FIPs>
            <FIPs travelReq="N">51750</FIPs>
            <FIPs travelReq="N">51121</FIPs>
            <FIPs travelReq="Y">51540</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="N">51019</FIPs>
            <FIPs travelReq="Y">51003</FIPs>
            <FIPs travelReq="N">51009</FIPs>
        </Service>
        <Service serviceZoom="-1" serviceName="Home-Based Service / Intensive In-Home">
            <FIPs travelReq="N">51191</FIPs>
            <FIPs travelReq="N">51173</FIPs>
            <FIPs travelReq="N">51185</FIPs>
            <FIPs travelReq="Y">51155</FIPs>
            <FIPs travelReq="N">51121</FIPs>
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N">51520</FIPs>
            <FIPs travelReq="Y">51750</FIPs>
            <FIPs travelReq="N">51540</FIPs>
            <FIPs travelReq="N">51003</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="N">51019</FIPs>
            <FIPs travelReq="Y">51009</FIPs>
            <FIPs travelReq="Y">51071</FIPs>
            <FIPs travelReq="N">51775</FIPs>
            <FIPs travelReq="N">51167</FIPs>
        </Service>
        <Service serviceZoom="-1" serviceName="HFW Intensive Care Coordination">
            <FIPs travelReq="N">51167</FIPs>
            <FIPs travelReq="N">51185</FIPs>
            <FIPs travelReq="N">51173</FIPs>
            <FIPs travelReq="N">51191</FIPs>
            <FIPs travelReq="Y">51197</FIPs>
            <FIPs travelReq="N">51520</FIPs>
            <FIPs travelReq="Y">51155</FIPs>
            <FIPs travelReq="Y">51021</FIPs>
            <FIPs travelReq="N">51105</FIPs>
            <FIPs travelReq="Y">51051</FIPs>
            <FIPs travelReq="N">51169</FIPs>
            <FIPs travelReq="Y">51027</FIPs>
            <FIPs travelReq="N">51195</FIPs>
            <FIPs travelReq="N">51720</FIPs>
            <FIPs travelReq="Y">51750</FIPs>
        </Service>
        <Service serviceZoom="-1" serviceName="Family Partnership Meeting">
            <FIPs travelReq="N">51520</FIPs>
            <FIPs travelReq="N">51191</FIPs>
            <FIPs travelReq="N">51173</FIPs>
            <FIPs travelReq="N">51185</FIPs>
            <FIPs travelReq="N">51167</FIPs>
            <FIPs travelReq="Y">51169</FIPs>
            <FIPs travelReq="Y">51105</FIPs>
            <FIPs travelReq="Y">51197</FIPs>
            <FIPs travelReq="Y">51021</FIPs>
            <FIPs travelReq="Y">51155</FIPs>
            <FIPs travelReq="Y">51750</FIPs>
            <FIPs travelReq="Y">51121</FIPs>
            <FIPs travelReq="Y">51775</FIPs>
            <FIPs travelReq="Y">51540</FIPs>
            <FIPs travelReq="Y">51161</FIPs>
            <FIPs travelReq="Y">51770</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="Y">51019</FIPs>
            <FIPs travelReq="Y">51009</FIPs>
        </Service>
        <Service serviceZoom="-1" serviceName="Trauma-Focused Cognitive Behavioral Therapy (TF-CBT)">
            <FIPs travelReq="N">51173</FIPs>
            <FIPs travelReq="N">51191</FIPs>
            <FIPs travelReq="N">51167</FIPs>
            <FIPs travelReq="N">51185</FIPs>
            <FIPs travelReq="N">51121</FIPs>
            <FIPs travelReq="N">51071</FIPs>
            <FIPs travelReq="N">51770</FIPs>
            <FIPs travelReq="N">51520</FIPs>
            <FIPs travelReq="N">51750</FIPs>
            <FIPs travelReq="N">51155</FIPs>
            <FIPs travelReq="N">51775</FIPs>
            <FIPs travelReq="N">51161</FIPs>
            <FIPs travelReq="N">51003</FIPs>
            <FIPs travelReq="N">51680</FIPs>
            <FIPs travelReq="Y">51019</FIPs>
            <FIPs travelReq="N">51009</FIPs>
            <FIPs travelReq="N">51540</FIPs>
            <FIPs travelReq="Y">51169</FIPs>
            <FIPs travelReq="Y">51195</FIPs>
            <FIPs travelReq="Y">51720</FIPs>
            <FIPs travelReq="Y">51105</FIPs>
        </Service>
    </Provider>
    <Provider id="23">
        <Name>Henrico Area Mental Health and Developmental Services</Name>
        <LastUpdated>2021-03-31</LastUpdated>
        <MapZoom>-1</MapZoom>
        <Website>http://henrico.us/mhds/</Website>
        <ContactName>Mike Walsh </ContactName>
        <ContactEmail>wal25@henrico.us</ContactEmail>
        <Office>
            <Lat>37.6539616</Lat>
            <Lng>-77.493552</Lng>
            <Street>10299 Woodman Road</Street>
            <City>Glen Allen </City>
            <State>VA</State>
            <Zip>23060</Zip>
            <Phone>(804) 727-8500</Phone>
            <Fax/>
        </Office>
        <Service serviceName="Multi-Systemic Therapy (MST)" serviceZoom="-1">
            <FIPs travelReq="N">51087</FIPs>
            <FIPs travelReq="Y">51085</FIPs>
            <FIPs travelReq="N">51036</FIPs>
            <FIPs travelReq="N">51127</FIPs>
        </Service>
    </Provider>
    <Provider id="5">
        <Name>Impact Living Services</Name>
        <LastUpdated>2021-01-12</LastUpdated>
        <MapZoom>-1</MapZoom>
        <Website>www.impactlivingservices.org</Website>
        <ContactName>Adam Pavao</ContactName>
        <ContactEmail>adam@impactlivingservices.org</ContactEmail>
        <Office>
            <Lat>37.36965</Lat>
            <Lng>-79.249741</Lng>
            <Street>316 Brook Park Place Suite A1</Street>
            <City>Forrest</City>
            <State>VA</State>
            <Zip>24551</Zip>
            <Phone>434-533-1088</Phone>
            <Fax>434-664-1177</Fax>
        </Office>
        <Office>
            <Lat>38.4207674</Lat>
            <Lng>-78.84069749999999</Lng>
            <Street>2262 Blue Stone Hills Dr. Suite C </Street>
            <City>Harrisonburg</City>
            <State>VA</State>
            <Zip>22801</Zip>
            <Phone>434-533-1088</Phone>
            <Fax>434-664-1177</Fax>
        </Office>
        <Office>
            <Lat>38.8247175</Lat>