<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DSPs [
<!--EDIT ONLY IN THE TXT FILE-->
<!--EXTERNAL DTD CALL DOES NOT PASS TO DOM-->
<!ELEMENT DSPs (Provider)>
<!ELEMENT Provider (Name, LastUpdated+, MapZoom?, Website?, ContactName?, ContactEmail?, Office+)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT LastUpdated (#PCDATA)>
<!ELEMENT MapZoom (#PCDATA)>
<!ELEMENT Website (#PCDATA)>
<!ELEMENT ContactName (#PCDATA)>
<!ELEMENT ContactEmail (#PCDATA)>
<!ELEMENT Office (Lat, Lng, Street, City, State, Zip, Phone, Fax)>
<!ELEMENT Lat (#PCDATA)>
<!ELEMENT Lng (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Fax (#PCDATA)>
<!ELEMENT Service (Locations?)>
<!ELEMENT FIPs (#PCDATA)>
<!-- Attribute Definitions-->
<!ATTLIST Provider id CDATA #REQUIRED>
<!ATTLIST Service serviceName CDATA #IMPLIED>
<!ATTLIST Service serviceZoom CDATA #IMPLIED>
<!ATTLIST Service serviceNote CDATA #IMPLIED>
<!ATTLIST FIPs travelReq (Y|N) "N">
<!ATTLIST FIPS languages CDATA #IMPLIED>
]>
<DSPs>
        <Provider id="0">
                <Name>Agape Counseling</Name>
                <MapZoom>0</MapZoom>
                <Website>agapecounselingva.com</Website>
                <ContactName>Shelly Baker-Scott, MS, LCSW, CSAC</ContactName>
                <ContactEmail>ShellyScott@agapecounselingva.com</ContactEmail>
                <Office>
                        <Lat>37.091</Lat>
                        <Lng>-76.387</Lng>
                        <Street>3221 Commander Shepard Blvd</Street>
                        <City>Hampton</City>
                        <State>VA</State>
                        <Zip>23666</Zip>
                        <Phone>(757) 244-3500</Phone>
                        <Fax></Fax>
                </Office>
                <Service serviceName="Casey Life Skills / Mentoring" serviceZoom="-1">
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                </Service>
        </Provider>
        <Provider id="1">
                <Name>Alpha Counsellors Service, Inc.</Name>
                <MapZoom>-1</MapZoom>
                <Website>www.alphacounsellors.com/</Website>
                <ContactName>Kyrystal Glover</ContactName>
                <ContactEmail>krystal.glover@alphacounsellors.com</ContactEmail>
                <Office>
                        <Lat>38.844</Lat>
                        <Lng>-77.114</Lng>
                        <Street>3701 S. George Mason Drive #805N</Street>
                        <City>Falls Church</City>
                        <State>VA</State>
                        <Zip>22041</Zip>
                        <Phone>(757) 876-2226</Phone>
                        <Fax></Fax>
                </Office>
                <Service serviceName="Psychology" serviceZoom="-1">
                        <FIPs travelReq="N">51610</FIPs>
                        <FIPs travelReq="N">51013</FIPs>
                        <FIPs travelReq="N">51510</FIPs>
                        <FIPs travelReq="N">51059</FIPs>
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51157</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                        <FIPs travelReq="N">51036</FIPs>
                        <FIPs travelReq="N">51073</FIPs>
                        <FIPs travelReq="N">51095</FIPs>
                        <FIPs travelReq="N">51097</FIPs>
                        <FIPs travelReq="N">51101</FIPs>
                        <FIPs travelReq="N">51115</FIPs>
                        <FIPs travelReq="N">51119</FIPs>
                        <FIPs travelReq="N">51127</FIPs>
                        <FIPs travelReq="N">51199</FIPs>
                        <FIPs travelReq="N">51735</FIPs>
                        <FIPs travelReq="N">51830</FIPs>
                        <FIPs travelReq="N">51033</FIPs>
                        <FIPs travelReq="N">51057</FIPs>
                        <FIPs travelReq="N">51085</FIPs>
                        <FIPs travelReq="N">51099</FIPs>
                        <FIPs travelReq="N">51103</FIPs>
                        <FIPs travelReq="N">51133</FIPs>
                        <FIPs travelReq="N">51159</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                        <FIPs travelReq="N">51193</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51003</FIPs>
                        <FIPs travelReq="N">51047</FIPs>
                        <FIPs travelReq="N">51065</FIPs>
                        <FIPs travelReq="N">51075</FIPs>
                        <FIPs travelReq="N">51079</FIPs>
                        <FIPs travelReq="N">51109</FIPs>
                        <FIPs travelReq="N">51113</FIPs>
                        <FIPs travelReq="N">51137</FIPs>
                        <FIPs travelReq="N">51540</FIPs>
                </Service>
                <Service serviceName="Outpatient YSB Services (CSOTP)" serviceZoom="-1">
                        <FIPs travelReq="N">51610</FIPs>
                        <FIPs travelReq="N">51013</FIPs>
                        <FIPs travelReq="N">51510</FIPs>
                        <FIPs travelReq="N">51059</FIPs>
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51157</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                        <FIPs travelReq="N">51036</FIPs>
                        <FIPs travelReq="N">51073</FIPs>
                        <FIPs travelReq="N">51095</FIPs>
                        <FIPs travelReq="N">51097</FIPs>
                        <FIPs travelReq="N">51101</FIPs>
                        <FIPs travelReq="N">51115</FIPs>
                        <FIPs travelReq="N">51119</FIPs>
                        <FIPs travelReq="N">51127</FIPs>
                        <FIPs travelReq="N">51199</FIPs>
                        <FIPs travelReq="N">51735</FIPs>
                        <FIPs travelReq="N">51830</FIPs>
                        <FIPs travelReq="N">51033</FIPs>
                        <FIPs travelReq="N">51057</FIPs>
                        <FIPs travelReq="N">51085</FIPs>
                        <FIPs travelReq="N">51099</FIPs>
                        <FIPs travelReq="N">51103</FIPs>
                        <FIPs travelReq="N">51133</FIPs>
                        <FIPs travelReq="N">51159</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                        <FIPs travelReq="N">51193</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51003</FIPs>
                        <FIPs travelReq="N">51047</FIPs>
                        <FIPs travelReq="N">51065</FIPs>
                        <FIPs travelReq="N">51075</FIPs>
                        <FIPs travelReq="N">51079</FIPs>
                        <FIPs travelReq="N">51109</FIPs>
                        <FIPs travelReq="N">51113</FIPs>
                        <FIPs travelReq="N">51137</FIPs>
                        <FIPs travelReq="N">51540</FIPs>
                </Service>
                <Service serviceName="Outpatient Substance Abuse" serviceZoom="-1">
                        <FIPs travelReq="N">51610</FIPs>
                        <FIPs travelReq="N">51013</FIPs>
                        <FIPs travelReq="N">51510</FIPs>
                        <FIPs travelReq="N">51059</FIPs>
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51157</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                        <FIPs travelReq="N">51036</FIPs>
                        <FIPs travelReq="N">51073</FIPs>
                        <FIPs travelReq="N">51095</FIPs>
                        <FIPs travelReq="N">51097</FIPs>
                        <FIPs travelReq="N">51101</FIPs>
                        <FIPs travelReq="N">51115</FIPs>
                        <FIPs travelReq="N">51119</FIPs>
                        <FIPs travelReq="N">51127</FIPs>
                        <FIPs travelReq="N">51199</FIPs>
                        <FIPs travelReq="N">51735</FIPs>
                        <FIPs travelReq="N">51830</FIPs>
                        <FIPs travelReq="N">51033</FIPs>
                        <FIPs travelReq="N">51057</FIPs>
                        <FIPs travelReq="N">51085</FIPs>
                        <FIPs travelReq="N">51099</FIPs>
                        <FIPs travelReq="N">51103</FIPs>
                        <FIPs travelReq="N">51133</FIPs>
                        <FIPs travelReq="N">51159</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                        <FIPs travelReq="N">51193</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51003</FIPs>
                        <FIPs travelReq="N">51047</FIPs>
                        <FIPs travelReq="N">51065</FIPs>
                        <FIPs travelReq="N">51075</FIPs>
                        <FIPs travelReq="N">51079</FIPs>
                        <FIPs travelReq="N">51109</FIPs>
                        <FIPs travelReq="N">51113</FIPs>
                        <FIPs travelReq="N">51137</FIPs>
                        <FIPs travelReq="N">51540</FIPs>
                </Service>
                <Service serviceName="Outpatient Services" serviceZoom="-1">
                        <FIPs travelReq="N">51610</FIPs>
                        <FIPs travelReq="N">51013</FIPs>
                        <FIPs travelReq="N">51510</FIPs>
                        <FIPs travelReq="N">51059</FIPs>
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51157</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                        <FIPs travelReq="N">51036</FIPs>
                        <FIPs travelReq="N">51073</FIPs>
                        <FIPs travelReq="N">51095</FIPs>
                        <FIPs travelReq="N">51097</FIPs>
                        <FIPs travelReq="N">51101</FIPs>
                        <FIPs travelReq="N">51115</FIPs>
                        <FIPs travelReq="N">51119</FIPs>
                        <FIPs travelReq="N">51127</FIPs>
                        <FIPs travelReq="N">51199</FIPs>
                        <FIPs travelReq="N">51735</FIPs>
                        <FIPs travelReq="N">51830</FIPs>
                        <FIPs travelReq="N">51033</FIPs>
                        <FIPs travelReq="N">51057</FIPs>
                        <FIPs travelReq="N">51085</FIPs>
                        <FIPs travelReq="N">51099</FIPs>
                        <FIPs travelReq="N">51103</FIPs>
                        <FIPs travelReq="N">51133</FIPs>
                        <FIPs travelReq="N">51159</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                        <FIPs travelReq="N">51193</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51003</FIPs>
                        <FIPs travelReq="N">51047</FIPs>
                        <FIPs travelReq="N">51065</FIPs>
                        <FIPs travelReq="N">51075</FIPs>
                        <FIPs travelReq="N">51079</FIPs>
                        <FIPs travelReq="N">51109</FIPs>
                        <FIPs travelReq="N">51113</FIPs>
                        <FIPs travelReq="N">51137</FIPs>
                        <FIPs travelReq="N">51540</FIPs>
                </Service>
                <Service serviceName="Intensive In-Home" serviceZoom="-1">
                        <FIPs travelReq="N">51610</FIPs>
                        <FIPs travelReq="N">51013</FIPs>
                        <FIPs travelReq="N">51510</FIPs>
                        <FIPs travelReq="N">51059</FIPs>
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51157</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                        <FIPs travelReq="N">51036</FIPs>
                        <FIPs travelReq="N">51073</FIPs>
                        <FIPs travelReq="N">51095</FIPs>
                        <FIPs travelReq="N">51097</FIPs>
                        <FIPs travelReq="N">51101</FIPs>
                        <FIPs travelReq="N">51115</FIPs>
                        <FIPs travelReq="N">51119</FIPs>
                        <FIPs travelReq="N">51127</FIPs>
                        <FIPs travelReq="N">51199</FIPs>
                        <FIPs travelReq="N">51735</FIPs>
                        <FIPs travelReq="N">51830</FIPs>
                        <FIPs travelReq="N">51033</FIPs>
                        <FIPs travelReq="N">51057</FIPs>
                        <FIPs travelReq="N">51085</FIPs>
                        <FIPs travelReq="N">51099</FIPs>
                        <FIPs travelReq="N">51103</FIPs>
                        <FIPs travelReq="N">51133</FIPs>
                        <FIPs travelReq="N">51159</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                        <FIPs travelReq="N">51193</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51003</FIPs>
                        <FIPs travelReq="N">51047</FIPs>
                        <FIPs travelReq="N">51065</FIPs>
                        <FIPs travelReq="N">51075</FIPs>
                        <FIPs travelReq="N">51079</FIPs>
                        <FIPs travelReq="N">51109</FIPs>
                        <FIPs travelReq="N">51113</FIPs>
                        <FIPs travelReq="N">51137</FIPs>
                        <FIPs travelReq="N">51540</FIPs>
                </Service>
                <Service serviceName="GPS / EM" serviceZoom="-1">
                        <FIPs travelReq="N">51610</FIPs>
                        <FIPs travelReq="N">51013</FIPs>
                        <FIPs travelReq="N">51510</FIPs>
                        <FIPs travelReq="N">51059</FIPs>
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51157</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                        <FIPs travelReq="N">51036</FIPs>
                        <FIPs travelReq="N">51073</FIPs>
                        <FIPs travelReq="N">51095</FIPs>
                        <FIPs travelReq="N">51097</FIPs>
                        <FIPs travelReq="N">51101</FIPs>
                        <FIPs travelReq="N">51115</FIPs>
                        <FIPs travelReq="N">51119</FIPs>
                        <FIPs travelReq="N">51127</FIPs>
                        <FIPs travelReq="N">51199</FIPs>
                        <FIPs travelReq="N">51735</FIPs>
                        <FIPs travelReq="N">51830</FIPs>
                        <FIPs travelReq="N">51033</FIPs>
                        <FIPs travelReq="N">51057</FIPs>
                        <FIPs travelReq="N">51085</FIPs>
                        <FIPs travelReq="N">51099</FIPs>
                        <FIPs travelReq="N">51103</FIPs>
                        <FIPs travelReq="N">51133</FIPs>
                        <FIPs travelReq="N">51159</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                        <FIPs travelReq="N">51193</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51003</FIPs>
                        <FIPs travelReq="N">51047</FIPs>
                        <FIPs travelReq="N">51065</FIPs>
                        <FIPs travelReq="N">51075</FIPs>
                        <FIPs travelReq="N">51079</FIPs>
                        <FIPs travelReq="N">51109</FIPs>
                        <FIPs travelReq="N">51113</FIPs>
                        <FIPs travelReq="N">51137</FIPs>
                        <FIPs travelReq="N">51540</FIPs>
                </Service>
                <Service serviceName="Casey Life Skills / Mentoring" serviceZoom="-1">
                        <FIPs travelReq="N">51610</FIPs>
                        <FIPs travelReq="N">51013</FIPs>
                        <FIPs travelReq="N">51510</FIPs>
                        <FIPs travelReq="N">51059</FIPs>
                        <FIPs travelReq="N">51061</FIPs>
                        <FIPs travelReq="N">51157</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                        <FIPs travelReq="N">51036</FIPs>
                        <FIPs travelReq="N">51073</FIPs>
                        <FIPs travelReq="N">51095</FIPs>
                        <FIPs travelReq="N">51097</FIPs>
                        <FIPs travelReq="N">51101</FIPs>
                        <FIPs travelReq="N">51115</FIPs>
                        <FIPs travelReq="N">51119</FIPs>
                        <FIPs travelReq="N">51127</FIPs>
                        <FIPs travelReq="N">51199</FIPs>
                        <FIPs travelReq="N">51735</FIPs>
                        <FIPs travelReq="N">51830</FIPs>
                        <FIPs travelReq="N">51033</FIPs>
                        <FIPs travelReq="N">51057</FIPs>
                        <FIPs travelReq="N">51085</FIPs>
                        <FIPs travelReq="N">51099</FIPs>
                        <FIPs travelReq="N">51103</FIPs>
                        <FIPs travelReq="N">51133</FIPs>
                        <FIPs travelReq="N">51159</FIPs>
                        <FIPs travelReq="N">51177</FIPs>
                        <FIPs travelReq="N">51179</FIPs>
                        <FIPs travelReq="N">51193</FIPs>
                        <FIPs travelReq="N">51630</FIPs>
                        <FIPs travelReq="N">51003</FIPs>
                        <FIPs travelReq="N">51047</FIPs>
                        <FIPs travelReq="N">51065</FIPs>
                        <FIPs travelReq="N">51075</FIPs>
                        <FIPs travelReq="N">51079</FIPs>
                        <FIPs travelReq="N">51109</FIPs>
                        <FIPs travelReq="N">51113</FIPs>
                        <FIPs travelReq="N">51137</FIPs>
                        <FIPs travelReq="N">51540</FIPs>
                </Service>
        </Provider>
        <Provider id="2">
                <Name>ANCHOR Commission</Name>
                <MapZoom>2</MapZoom>
                <Website></Website>
                <ContactName>Ricky Walker</ContactName>
                <ContactEmail>ricky.walker@anchor-services.org</ContactEmail>
                <Office>
                        <Lat>36.687</Lat>
                        <Lng>-79.868</Lng>
                        <Street>100 Cleveland Avenue</Street>
                        <City>Martinsville</City>
                        <State>VA</State>
                        <Zip>24112</Zip>
                        <Phone>(276) 634-2919</Phone>
                        <Fax></Fax>
                </Office>
                <Service serviceName="Outpatient Services" serviceZoom="-1">
                        <FIPs travelReq="N">51067</FIPs>
                        <FIPs travelReq="N">51143</FIPs>
                        <FIPs travelReq="N">51590</FIPs>
                </Service>
                <Service serviceName="Outpatient Services" serviceZoom="-1">
                        <FIPs travelReq="N">51067</FIPs>
                        <FIPs travelReq="N">51143</FIPs>
                        <FIPs travelReq="N">51590</FIPs>
                </Service>
        </Provider>
        <Provider id="3">
                <Name>Blue Ridge Behavioral Healthcare</Name>
                <MapZoom>1</MapZoom>
                <Website>www.brbh.org</Website>
                <ContactName>Cathy L. Brown, LCSW</ContactName>
                <ContactEmail>cbrown@brbh.org</ContactEmail>
                <Office>
                        <Lat>37.266</Lat>
                        <Lng>-80.006</Lng>
                        <Street>3517 Brandon Ave., SW</Street>
                        <City>Roanoke</City>
                        <State>VA</State>
                        <Zip>24018</Zip>
                        <Phone>(540) 981-1102 ext. 2248</Phone>
                        <Fax></Fax>
                </Office>
                <Service serviceName="Outpatient Substance Abuse" serviceZoom="1">
                        <!-- Craig and Botetourt -->
                        <FIPs travelReq="N">51045</FIPs>
                        <FIPs travelReq="N">51023</FIPs>
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
                <Service serviceName="Trauma Assessment" serviceZoom="1">
                        <!-- Craig and Botetourt -->
                        <FIPs travelReq="N">51045</FIPs>
                        <FIPs travelReq="N">51023</FIPs>
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
                <Service serviceName="Outpatient Services" serviceZoom="1">
                        <!-- Craig and Botetourt -->
                        <FIPs travelReq="N">51045</FIPs>
                        <FIPs travelReq="N">51023</FIPs>
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
                <Service serviceName="Casey Life Skills / Mentoring" serviceZoom="1">
                        <!-- Craig and Botetourt -->
                        <FIPs travelReq="N">51045</FIPs>
                        <FIPs travelReq="N">51023</FIPs>
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
        </Provider>
        <Provider id="4">
                <Name>Braley and Thompson, Inc.</Name>
                <MapZoom>2</MapZoom>
                <Website>braleyandthompson.com</Website>
                <ContactName>Mary Struzinzky</ContactName>
                <ContactEmail>mstruzinsky@rescare.com</ContactEmail>
                <Office>
                        <Lat>38.227</Lat>
                        <Lng>-85.573</Lng>
                        <Street>9901 Linn Station Road</Street>
                        <City>Louisville</City>
                        <State>KY</State>
                        <Zip>40223</Zip>
                        <Phone>(502) 394-2161</Phone>
                        <Fax></Fax>
                </Office>
                <Service serviceName="Psychological" serviceZoom="2">
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
                <Service serviceName="Trauma Assessment" serviceZoom="2">
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
                <Service serviceName="Outpatient Services" serviceZoom="2">
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
                <Service serviceName="Casey Life Skills / Mentoring" serviceZoom="2">
                        <!-- All of CSU23 -->
                        <FIPs travelReq="N">51161</FIPs>
                        <FIPs travelReq="N">51775</FIPs>
                        <!-- CSU23A Roanoke -->
                        <FIPs travelReq="N">51770</FIPs>
                </Service>
        </Provider>
        <Provider id ="6">
                <Name>Bridging the Gap Family Services</Name>
                <MapZoom>-1</MapZoom>
                <Website>www.btgfs.org/</Website>
                <ContactName>Rahmell Dash</ContactName>
                <ContactEmail>info@btgfs.org</ContactEmail>
                <Office>
                        <Lat>38.801</Lat>
                        <Lng>-77.51</Lng>
                        <Street>10432 Balls Ford Rd Suite 383</Street>
                        <City>Manassas</City>
                        <State>VA</State>
                        <Zip>20109</Zip>
                        <Phone>(703) 881-7783</Phone>
                        <Fax>(703) 337-0320</Fax>
                </Office>
                <Service serviceName="Intensive In-Home" serviceZoom="-1">
                        <FIPs travelReq="N">51107</FIPs>
                        <FIPs travelReq="N">51043</FIPs>
                        <FIPs travelReq="N">51069</FIPs>
                        <FIPs travelReq="N">51139</FIPs>
                        <FIPs travelReq="N">51165</FIPs>
                        <FIPs travelReq="N">51171</FIPs>
                        <FIPs travelReq="N">51187</FIPs>
                        <FIPs travelReq="N">51660</FIPs>
                        <FIPs travelReq="N">51840</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                </Service>
                <Service serviceName="Casey Life Skills / Mentoring" serviceZoom="-1">
                        <FIPs travelReq="N">51107</FIPs>
                        <FIPs travelReq="N">51043</FIPs>
                        <FIPs travelReq="N">51069</FIPs>
                        <FIPs travelReq="N">51139</FIPs>
                        <FIPs travelReq="N">51165</FIPs>
                        <FIPs travelReq="N">51171</FIPs>
                        <FIPs travelReq="N">51187</FIPs>
                        <FIPs travelReq="N">51660</FIPs>
                        <FIPs travelReq="N">51840</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                </Service>
                <Service serviceName="Gang Intervention" serviceZoom="-1">
                        <FIPs travelReq="N">51107</FIPs>
                        <FIPs travelReq="N">51043</FIPs>
                        <FIPs travelReq="N">51069</FIPs>
                        <FIPs travelReq="N">51139</FIPs>
                        <FIPs travelReq="N">51165</FIPs>
                        <FIPs travelReq="N">51171</FIPs>
                        <FIPs travelReq="N">51187</FIPs>
                        <FIPs travelReq="N">51660</FIPs>
                        <FIPs travelReq="N">51840</FIPs>
                        <FIPs travelReq="N">51153</FIPs>
                        <FIPs travelReq="N">51683</FIPs>
                        <FIPs travelReq="N">51685</FIPs>
                </Service>
        </Provider>
</DSPs>